from project.app.professors.domain.models.professorsModel import (
    ProfesorModel
)
from project.shared.domain.utils.updateOrCreate import (
    update_or_create
)
from project.shared.domain.ports.seederPort import SeederPort

class ProfesorSeeder(SeederPort):

    profesors = [
        {
            "fullname": "ARIAS LONDOÑO ALEXANDER",
            "identification_card": 98648261,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA ELECTRÓNICA",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Ingeniería - Ingeniería de Sistemas",
            "undergraduate_degree": "Ingeniero Electrónico",
            "partnership": "CARRERA",
            "institutional_email": "alexanderarias@itm.edu.co",
            "personal_email": "profeitm@gmail.com",
            "email_with_domain": "alexanderarias8261@correo.itm.edu.co",
            "faculty_location": "Bloque L- 304 (Sede Fraternidad)"
        },
        {
            "fullname": "CASTRILLON JIMENEZ ELKIN ALBERTO",
            "identification_card": 8405884,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN GESTIÓN DE REDES DE TELECOMUNICACIONES",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Gestión Energética Industrial",
            "undergraduate_degree": "Ingeniero en Instrumentación y Control",
            "partnership": "CARRERA",
            "institutional_email": "elkincastrillon@itm.edu.co",
            "personal_email": "elkincastrillon5884@correo.itm.edu.co",
            "email_with_domain": "elkincastrillon5884@correo.itm.edu.co",
            "faculty_location": "Bloque N-405 (Sede Fraternidad)"
        },
        {
            "fullname": "CASTRO OSPINA ANDRÉS EDUARDO",
            "identification_card": 1053792705,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN AUTOMATIZACIÓN ELECTRÓNICA",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Ingeniería - Automatización Industrial",
            "undergraduate_degree": "Ingeniero Electrónico",
            "partnership": "CARRERA",
            "institutional_email": "andrescastro@itm.edu.co",
            "personal_email": "",
            "email_with_domain": "andrescastro2705@correo.itm.edu.co",
            "faculty_location": "Laboratorio de Máquinas Inteligentes y Reconocimiento de Patrones - Parque-I"
        },
        {
            "fullname": "LOPEZ GIRALDO FRANCISCO EUGENIO",
            "identification_card": 98569978,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA EN TELECOMUNICACIONES",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctor en Física",
            "undergraduate_degree": "Físico",
            "partnership": "CARRERA",
            "institutional_email": "franciscolopez@itm.edu.co",
            "personal_email": "flopezgi1@gmail.com",
            "email_with_domain": "franciscolopez9978@correo.itm.edu.co",
            "faculty_location": "M-212 - laboratorio de Física M-103 - laboratorio de óptica, fotónica y visión artificial M9811"
        },
        {
            "fullname": "MARTINEZ CIRO ROGER ALEXANDER",
            "identification_card": 1040260199,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN GESTIÓN DE REDES DE TELECOMUNICACIONES",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Automatización y Control Industrial",
            "undergraduate_degree": "Ingeniero de Telecomunicaciones",
            "partnership": "CARRERA",
            "institutional_email": "rogermartinez@itm.edu.co",
            "personal_email": "alexanders-rogers@hotmail.com",
            "email_with_domain": "rogermartinez0199@correo.itm.edu.co",
            "faculty_location": "Bloque M-212 (Sede Fraternidad)"
        },
        {
            "fullname": "MONCADA ACEVEDO MARIA ELENA",
            "identification_card": 43629910,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA ELECTRÓNICA",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctor en Ingeniería",
            "undergraduate_degree": "Ingeniero Electrónico",
            "partnership": "CARRERA",
            "institutional_email": "mariamoncada@itm.edu.co",
            "personal_email": "mariaema1@gmail.com",
            "email_with_domain": "mariamoncada9910@correo.itm.edu.co",
            "faculty_location": "Parque I, Laboratorio de Energía Eléctrica y Potencia"
        },
        {
            "fullname": "MORANTES GUZMAN LUIS JAVIER",
            "identification_card": 88262193,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN AUTOMATIZACIÓN ELECTRÓNICA",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Ingeniería - Automatización Industrial",
            "undergraduate_degree": "Ingeniero Electrónico",
            "partnership": "CARRERA",
            "institutional_email": "luismorantes@itm.edu.co",
            "personal_email": "luismorantes@itm.edu.co",
            "email_with_domain": "luismorantes2193@correo.itm.edu.co",
            "faculty_location": "Parque I - Lab de Sistemas de Control y Robótica"
        },
        {
            "fullname": "ORTIZ VALENCIA PAULA ANDREA",
            "identification_card": 43613885,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN AUTOMATIZACIÓN ELECTRÓNICA",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctor en Ingeniería",
            "undergraduate_degree": "Ingeniero en Instrumentación y Control",
            "partnership": "CARRERA",
            "institutional_email": "paulaortiz@itm.edu.co",
            "personal_email": "portizv@gmail.com",
            "email_with_domain": "paulaortiz3885@correo.itm.edu.co",
            "faculty_location": "Bloque M sótano 1 ( pero yo estoy en teletrabajo)"
        },
        {
            "fullname": "SERNA GARCES SERGIO IGNACIO",
            "identification_card": 98553427,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA EN TELECOMUNICACIONES",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctor en Ingeniería",
            "undergraduate_degree": "Ingeniero Electrónico",
            "partnership": "CARRERA",
            "institutional_email": "sergioserna@itm.edu.co",
            "personal_email": "ignacio.serna@udea.edu.co",
            "email_with_domain": "sergioserna3427@correo.itm.edu.co",
            "faculty_location": "Oficina ASODITEM 117-F (Bloque L, piso 2), Laboratorio de Electrónica y Energías Renovables (Parque I), Casa."
        },
        {
            "fullname": "YEPES ZULUAGA SARA MARIA",
            "identification_card": 43165096,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN GESTIÓN DE REDES DE TELECOMUNICACIONES",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Ingeniería Electrónica",
            "undergraduate_degree": "Ingeniero Electrónico",
            "partnership": "CARRERA",
            "institutional_email": "sarayepes@itm.edu.co",
            "personal_email": "sarayepes@itm.edu.co",
            "email_with_domain": "sarayepes5096@correo.itm.edu.co",
            "faculty_location": "Bloque L- 304 (Sede Fraternidad)"
        },
        {
            "fullname": "ALVAREZ SALAZAR JOHNY ANTONIO",
            "identification_card": 98536389,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA EN TELECOMUNICACIONES",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctorado en Ciencias de la Educación",
            "undergraduate_degree": "Ingeniero Electromecánico",
            "partnership": "OCASIONAL",
            "institutional_email": "johnyalvarez@itm.edu.co",
            "personal_email": "johnyalvarez@itm.edu.co",
            "email_with_domain": "johnyalvarez6389@correo.itm.edu.co",
            "faculty_location": "Bloque M sótano 1"
        },
        {
            "fullname": "BETANCUR PEREZ ANDRÉS FELIPE",
            "identification_card": 98702799,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA EN TELECOMUNICACIONES",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Ingeniería de Telecomunicaciones",
            "undergraduate_degree": "Ingeniero Electrónico",
            "partnership": "OCASIONAL",
            "institutional_email": "andresbetancur@itm.edu.co",
            "personal_email": "andresfbp@gmail.com",
            "email_with_domain": "andresbetancur2799@correo.itm.edu.co",
            "faculty_location": "Bloque M-212 (Sede Fraternidad)"
        },
        {
            "fullname": "CARMONA CASTRO MAURICIO ALONSO",
            "identification_card": 71675221,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN GESTIÓN DE REDES DE TELECOMUNICACIONES",
            "highest_education_level": "Especialización",
            "degree_obtained": "Especialización en Gestión Energética Industrial",
            "undergraduate_degree": "Ingeniero Industrial",
            "partnership": "OCASIONAL",
            "institutional_email": "mauriciocarmonac@itm.edu.co",
            "personal_email": "mauriciocarmonac@itm.edu.co",
            "email_with_domain": "mauriciocarmona5221@correo.itm.edu.co",
            "faculty_location": "Bloque M sótano 1"
        },
        {
            "fullname": "CASTRILLON FORERO JAVIER ERNESTO",
            "identification_card": 71782916,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA ELECTRÓNICA",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Desarrollo de Producto y Modelado Digital",
            "undergraduate_degree": "Ingeniero Industrial",
            "partnership": "OCASIONAL",
            "institutional_email": "javiercastrillon@itm.edu.co",
            "personal_email": "javiercastrillon@itm.edu.co",
            "email_with_domain": "javiercastrillon2916@correo.itm.edu.co",
            "faculty_location": ""
        },
        {
            "fullname": "GARCÍA PINEDA VANESSA",
            "identification_card": 1214718967,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA EN TELECOMUNICACIONES",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Gestión de la Innovación, Tecnología, Cooperación y Desarrollo Regional",
            "undergraduate_degree": "Ingeniera de Telecomunicaciones",
            "partnership": "OCASIONAL",
            "institutional_email": "vanessagarciap@itm.edu.co",
            "personal_email": "vanessagarcia8967@correo.itm.edu.co",
            "email_with_domain": "vanessagarcia8967@correo.itm.edu.co",
            "faculty_location": "Bloque M-212 (Sede Fraternidad)"
        },
        {
            "fullname": "GOEZ MORA MANUEL MAURICIO",
            "identification_card": 1037603599,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "TECNOLOGÍA EN AUTOMATIZACIÓN ELECTRÓNICA",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctor en Ingeniería",
            "undergraduate_degree": "Ingeniería de Control",
            "partnership": "OCASIONAL",
            "institutional_email": "manuelgoez@itm.edu.co",
            "personal_email": "mmgoezm@gmail.com",
            "email_with_domain": "manuelgoez3599@correo.itm.edu.co",
            "faculty_location": "Bloque M-212 (Sede Fraternidad)"
        },
        {
            "fullname": "GOMEZ YEPES VICTOR HUGO",
            "identification_card": 70253081,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA ELECTRÓNICA",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctor en Filosofía",
            "undergraduate_degree": "Filósofo",
            "partnership": "OCASIONAL",
            "institutional_email": "victorgomez@itm.edu.co",
            "personal_email": "victorgomez@itm.edu.co",
            "email_with_domain": "victorgomez3007@correo.itm.edu.co",
            "faculty_location": "Sala de profesores de cátedra Fraternidad Lunes, martes y miércoles. G C103 Robledo Jueves y viernes."
        },
        {
            "fullname": "GONZALEZ VALENCIA ESTEBAN",
            "identification_card": 1128384302,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA EN TELECOMUNICACIONES",
            "highest_education_level": "Doctorado",
            "degree_obtained": "Doctor en Ciencias Física",
            "undergraduate_degree": "Ingeniero Físico",
            "partnership": "OCASIONAL",
            "institutional_email": "estebangonzalez@itm.edu.co",
            "personal_email": "egonzalv@gmail.com",
            "email_with_domain": "estebangonzalez4302@correo.itm.edu.co",
            "faculty_location": "Bloque M-212 (Sede Fraternidad)"
        },
        {
            "fullname": "GRAJALES BUSTAMANTE JUAN DAVID",
            "identification_card": 70325806,
            "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
            "program": "INGENIERÍA EN TELECOMUNICACIONES",
            "highest_education_level": "Maestría",
            "degree_obtained": "Magíster en Seguridad Informática",
            "undergraduate_degree": "Ingeniero de Telecomunicaciones",
            "partnership": "OCASIONAL",
            "institutional_email": "juangrajales@itm.edu.co",
            "personal_email": "juangrajales5806@correo.itm.edu.co",
            "email_with_domain": "juangrajales5806@correo.itm.edu.co",
            "faculty_location": "Bloque M sótano 1"
        },
        {
        "fullname": "GUARNIZO LEMUS CRISTIAN",
        "identification_card": 10034133,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA ELECTRÓNICA",
        "highest_education_level": "Doctorado",
        "degree_obtained": "Doctor en Ingeniería",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "cristianguarnizo@itm.edu.co",
        "personal_email": "cdguarnizo@hotmail.com",
        "email_with_domain": "cristianguarnizo4133@correo.itm.edu.co",
        "faculty_location": "Parque I - Laboratorio de Sistemas de Control y Robótica"
    },
    {
        "fullname": "MARQUEZ VILORIA DAVID ANDRES",
        "identification_card": 16079570,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Magíster en Ingeniería Eléctrica",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "davidmarquez@itm.edu.co",
        "personal_email": "davidmarquez@itm.edu.co",
        "email_with_domain": "davidmarquez9570@correo.itm.edu.co",
        "faculty_location": "Laboratorio de sistemas de control y robótica, Parque-I"
    },
    {
        "fullname": "MEJÍA ARANGO JUAN GUILLERMO",
        "identification_card": 98514998,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA ELECTRÓNICA",
        "highest_education_level": "Doctorado",
        "degree_obtained": "Doctorado en Ciencias de la Educación",
        "undergraduate_degree": "Ingeniero Electricista",
        "partnership": "OCASIONAL",
        "institutional_email": "juanmejia@itm.edu.co",
        "personal_email": "juanmejiaar@gmail.com",
        "email_with_domain": "juanmejia4998@correo.itm.edu.co",
        "faculty_location": "Bloque L- 304 (Sede Fraternidad)"
    },
    {
        "fullname": "MONTES GRANADA WILLER FERNEY",
        "identification_card": 15336658,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Maestría en Electrónica",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "willermontes@itm.edu.co",
        "personal_email": "wfmontes@gmail.com",
        "email_with_domain": "willermontes6658@correo.itm.edu.co",
        "faculty_location": "Bloque M sótano 1"
    },
    {
        "fullname": "MONTOYA BENITEZ ALBER OSWALDO",
        "identification_card": 98606628,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Magíster en Ingeniería de Telecomunicaciones",
        "undergraduate_degree": "Ingeniería de Control",
        "partnership": "OCASIONAL",
        "institutional_email": "albermontoya@itm.edu.co",
        "personal_email": "albertmontoya912@gmail.com",
        "email_with_domain": "albermontoya6628@correo.itm.edu.co",
        "faculty_location": "Bloque M-212 (Sede Fraternidad)"
    },
    {
        "fullname": "NIETO MORA DANIEL ALEXIS",
        "identification_card": 1017222725,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA ELECTRÓNICA",
        "highest_education_level": "Maestría",
        "degree_obtained": "Magister en Automatización y Control Industrial",
        "undergraduate_degree": "Ingeniería Mecatrónica",
        "partnership": "OCASIONAL",
        "institutional_email": "danielnieto@itm.edu.co",
        "personal_email": "alexis.0894@hotmail.com",
        "email_with_domain": "danielnieto2725@correo.itm.edu.co",
        "faculty_location": "Laboratorio de Máquinas Inteligentes y Reconocimiento de Patrones MIRP - Parque I"
    },
    {
        "fullname": "OSPINA CIFUENTES BAYRON JESIT",
        "identification_card": 98505501,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Magíster en Ingeniería de Telecomunicaciones",
        "undergraduate_degree": "Ingeniero de Sistemas",
        "partnership": "OCASIONAL",
        "institutional_email": "bayronospina@itm.edu.co",
        "personal_email": "bayronospina@itm.edu.co",
        "email_with_domain": "bayronospina5501@correo.itm.edu.co",
        "faculty_location": "Bloque M-212 (Sede Fraternidad)"
    },
    {
        "fullname": "OSSA MOLINA OSCAR DAVID",
        "identification_card": 1152195365,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Maestría en Automatización y Control Industrial",
        "undergraduate_degree": "Ingeniero de Telecomunicaciones",
        "partnership": "OCASIONAL",
        "institutional_email": "oscarossa@itm.edu.co",
        "personal_email": "oscarossa5365@correo.itm.edu.co",
        "email_with_domain": "oscarossa5365@correo.itm.edu.co",
        "faculty_location": "Bloque M-212 (Sede Fraternidad)"
    },
    {
        "fullname": "RESTREPO CUESTAS BONIE JOHANA",
        "identification_card": 24694065,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA ELECTRÓNICA",
        "highest_education_level": "Doctorado",
        "degree_obtained": "Doctora en Ingeniería Automática",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "bonierestrepo@itm.edu.co",
        "personal_email": "bonierestrepo@itm.edu.co",
        "email_with_domain": "bonierestrepo4065@correo.itm.edu.co",
        "faculty_location": "Laboratorio de Simulación, Modelamiento y Prototipado ubicado en Parque I"
    },
    {
        "fullname": "REYES VERA ERICK ESTEFEN",
        "identification_card": 1017125415,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Doctorado",
        "degree_obtained": "Doctor en Ingeniería",
        "undergraduate_degree": "Ingeniero Físico",
        "partnership": "OCASIONAL",
        "institutional_email": "erickreyes@itm.edu.co",
        "personal_email": "erickreyes@itm.edu.co",
        "email_with_domain": "erickreyes5415@correo.itm.edu.co",
        "faculty_location": "Bloque M-212 (Sede Fraternidad)"
    },
    {
        "fullname": "ROJAS MONTANO JHON JAIRO",
        "identification_card": 1116917420,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "TECNOLOGÍA EN AUTOMATIZACIÓN ELECTRÓNICA",
        "highest_education_level": "Maestría",
        "degree_obtained": "Maestría en Automatización y Control Industrial",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "jhonrojas@itm.edu.co",
        "personal_email": "jhonrojas@itm.edu.co",
        "email_with_domain": "jhonrojas7420@correo.itm.edu.co",
        "faculty_location": ""
    },
    {
        "fullname": "ROLDAN VASCO SEBASTIAN",
        "identification_card": 1037570818,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA ELECTRÓNICA",
        "highest_education_level": "Doctorado",
        "degree_obtained": "Doctor en Ingeniería Electrónica y de Computación",
        "undergraduate_degree": "Bioingeniería",
        "partnership": "OCASIONAL",
        "institutional_email": "sebastianroldan@itm.edu.co",
        "personal_email": "sebastianroldan@itm.edu.co",
        "email_with_domain": "sebastianroldan0818@correo.itm.edu.co",
        "faculty_location": "Parque I - Simulación, modelamiento y prototipos"
    },
    {
        "fullname": "SERNA GUARIN LEONARDO",
        "identification_card": 98583374,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Maestría en Automatización y Control Industrial",
        "undergraduate_degree": "Ingeniero de Sistemas",
        "partnership": "OCASIONAL",
        "institutional_email": "leonardoserna@itm.edu.co",
        "personal_email": "leonardoserna@itm.edu.co",
        "email_with_domain": "leonardoserna3374@correo.itm.edu.co",
        "faculty_location": "Bloque M sótano 1"
    },
    {
        "fullname": "SOTO PERDOMO JUAN SEBASTIÁN",
        "identification_card": 1079412389,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "TECNOLOGÍA EN GESTIÓN DE REDES DE TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Maestría en Automatización y Control Industrial",
        "undergraduate_degree": "Físico",
        "partnership": "OCASIONAL",
        "institutional_email": "juansotop@itm.edu.co",
        "personal_email": "juansoto319998@correo.itm.edu.co",
        "email_with_domain": "juansoto319998@correo.itm.edu.co",
        "faculty_location": "Bloque M-212 (Sede Fraternidad)"
    },
    {
        "fullname": "SUAREZ ALVAREZ FABIO LEON",
        "identification_card": 71582563,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Magíster en Gestión Energética",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "fabiosuarez@itm.edu.co",
        "personal_email": "fabiosuarez@itm.edu.co",
        "email_with_domain": "fabiosuarez2563@correo.itm.edu.co",
        "faculty_location": "Bloque L- 304 (Sede Fraternidad)"
    },
    {
        "fullname": "TOBÓN MEJÍA ANDRÉS FELIPE",
        "identification_card": 71778382,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA EN TELECOMUNICACIONES",
        "highest_education_level": "Maestría",
        "degree_obtained": "Maestría en Automatización y Control Industrial",
        "undergraduate_degree": "Ingeniero en Instrumentación y Control",
        "partnership": "OCASIONAL",
        "institutional_email": "andrestobon@itm.edu.co",
        "personal_email": "andrestobon@itm.edu.co",
        "email_with_domain": "andrestobon8382@correo.itm.edu.co",
        "faculty_location": "Parque I, Fraternidad, Lab. Electrónica y energías renovables"
    },
    {
        "fullname": "VALLEJO VALENCIA MARCELA",
        "identification_card": 32182736,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "TECNOLOGÍA EN AUTOMATIZACIÓN ELECTRÓNICA",
        "highest_education_level": "Maestría",
        "degree_obtained": "Magíster en Ingeniería",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "marcelavallejo@itm.edu.co",
        "personal_email": "mvallejov@gmail.com",
        "email_with_domain": "marcelavallejo2736@correo.itm.edu.co",
        "faculty_location": "Fraternidad (Bloque M sótano 1), Robledo (F-201, Laboratorio Amysod)"
    },
    {
        "fullname": "VILLEGAS CEBALLOS JUAN PABLO",
        "identification_card": 1017192320,
        "department": "ELECTRÓNICA Y TELECOMUNICACIONES",
        "program": "INGENIERÍA ELECTRÓNICA",
        "highest_education_level": "Maestría",
        "degree_obtained": "Ingeniero Electrónico",
        "undergraduate_degree": "Ingeniero Electrónico",
        "partnership": "OCASIONAL",
        "institutional_email": "juanvillegas@itm.edu.co",
        "personal_email": "juanvillegas@itm.edu.co",
        "email_with_domain": "juanvillegas2320@correo.itm.edu.co",
        "faculty_location": "Parque I - Laboratorio de electrónica y energías renovables."
    }
    ]

    def handle(self):
        try:
            for profesor in self.profesors:
                update_or_create(
                    session=self.session,
                    model=ProfesorModel,
                    keys={
                        "identification_card": profesor.get("identification_card")
                    },
                    data=profesor
                )
        except Exception as error:
            self.session.rollback()
            print(f"Error in the Seeder ProfesorSeeder: {error}")
        finally:
            self.session.close()
