"""Added role in professors

Revision ID: 4f011b61898f
Revises: 11404e8ec164
Create Date: 2025-02-18 22:35:43.921548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f011b61898f'
down_revision: Union[str, None] = '11404e8ec164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('role', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'role')
    # ### end Alembic commands ###
