"""Added schedules table

Revision ID: 68ac0028e010
Revises: e0f1d0814701
Create Date: 2025-02-17 16:34:35.039289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ac0028e010'
down_revision: Union[str, None] = 'e0f1d0814701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=15), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('schedule', sa.String(length=150), nullable=False),
    sa.Column('classroom', sa.String(length=150), nullable=False),
    sa.Column('academic_program', sa.String(length=40), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, onupdate=sa.func.now()),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_group_id'), 'schedules', ['group_id'], unique=True)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_group_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
