"""Initial migration

Revision ID: e0f1d0814701
Revises: 
Create Date: 2025-02-16 22:31:34.866379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f1d0814701'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('identification_card', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('program', sa.String(length=80), nullable=False),
    sa.Column('highest_education_level', sa.String(length=20), nullable=False),
    sa.Column('degree_obtained', sa.String(length=100), nullable=False),
    sa.Column('undergraduate_degree', sa.String(length=80), nullable=False),
    sa.Column('partnership', sa.String(length=15), nullable=False),
    sa.Column('institutional_email', sa.String(length=100), nullable=False),
    sa.Column('personal_email', sa.String(length=100), nullable=False),
    sa.Column('email_with_domain', sa.String(length=100), nullable=False),
    sa.Column('faculty_location', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, onupdate=sa.func.now()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_with_domain'),
    sa.UniqueConstraint('institutional_email'),
    sa.UniqueConstraint('personal_email')
    )
    op.create_index(op.f('ix_profesors_id'), 'profesors', ['id'], unique=False)
    op.create_index(op.f('ix_profesors_identification_card'), 'profesors', ['identification_card'], unique=True)
    op.create_table('logged-in_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('hash_password', sa.Text(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, onupdate=sa.func.now()),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_logged-in_users_id'), 'logged-in_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logged-in_users_id'), table_name='logged-in_users')
    op.drop_table('logged-in_users')
    op.drop_index(op.f('ix_profesors_identification_card'), table_name='profesors')
    op.drop_index(op.f('ix_profesors_id'), table_name='profesors')
    op.drop_table('profesors')
    # ### end Alembic commands ###
