"""Initial migration

Revision ID: ecb1a3a91675
Revises: 
Create Date: 2025-02-19 16:47:09.817178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb1a3a91675'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('identification_card', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('program', sa.String(length=80), nullable=False),
    sa.Column('highest_education_level', sa.String(length=20), nullable=False),
    sa.Column('degree_obtained', sa.String(length=100), nullable=False),
    sa.Column('undergraduate_degree', sa.String(length=80), nullable=False),
    sa.Column('partnership', sa.String(length=15), nullable=False),
    sa.Column('institutional_email', sa.String(length=100), nullable=False),
    sa.Column('personal_email', sa.String(length=100), nullable=False),
    sa.Column('email_with_domain', sa.String(length=100), nullable=False),
    sa.Column('faculty_location', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, onupdate=sa.func.now()),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professors_id'), 'professors', ['id'], unique=False)
    op.create_index(op.f('ix_professors_identification_card'), 'professors', ['identification_card'], unique=False)
    op.create_table('logged-in_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('hash_password', sa.Text(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, onupdate=sa.func.now()),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_logged-in_users_id'), 'logged-in_users', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=15), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('schedule', sa.String(length=150), nullable=False),
    sa.Column('classroom', sa.String(length=150), nullable=False),
    sa.Column('academic_program', sa.String(length=40), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, onupdate=sa.func.now()),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_group_id'), 'schedules', ['group_id'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_group_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_logged-in_users_id'), table_name='logged-in_users')
    op.drop_table('logged-in_users')
    op.drop_index(op.f('ix_professors_identification_card'), table_name='professors')
    op.drop_index(op.f('ix_professors_id'), table_name='professors')
    op.drop_table('professors')
    # ### end Alembic commands ###
