name: Consulting Schedules

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
      continue-on-error: false

    - name: Deploy with Docker Compose
      run: docker-compose up -d
      continue-on-error: false

    - name: Verify services
      run: |
        docker-compose ps

    - name: Wait for services to be ready
      run: |
        sleep 10
    
    - name: Run Alembic migrations
      run: |
        docker-compose exec backend alembic upgrade head

    - name: Run Seeders
      run: |
        flask dbseed
